version: '3'
services:
    app:
        container_name: highload
        build:
            context: ./docker/php-fpm
            args:
                APP_DEBUG: ${APP_DEBUG}
                TZ: ${TZ}
        networks:
            - highload
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '9000:9000'
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - .:/var/www/highload:rw,cached
        depends_on:
            - redis
            - memcached
            - db-master
            - db-email
            - db-sms
            - db-slave-3
            - db-slave-4

    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
            args:
                NGINX_HOST: ${NGINX_HOST}
        ports:
            - '80:80'
            - '443:443'
        networks:
            - highload
        depends_on:
            - app
        volumes:
            - ./public:/var/www/highload/public
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/nginx_log:/var/log/nginx
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        command: /bin/bash -c "exec nginx -g 'daemon off;'"

    redis:
        container_name: redis
        image: redis:latest
        networks:
            - highload
        ports:
            - ${REDIS_PORT}:6379

    memcached:
        container_name: memcached
        image: memcached:latest
        networks:
            - highload
        ports:
            - ${MEMCACHED_PORT}:11211

    db-master:
        container_name: db-master
        image: mariadb:latest
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - ./docker/db/master/master.sql:/docker-entrypoint-initdb.d/start.sql
            - ./docker/db/master/maria.master.cnf:/etc/mysql/conf.d/maria.master.cnf
            - ./docker/db/master/.data/mysql:/var/lib/mysql:rw
        networks:
            - highload

    db-email:
        container_name: db_email
        image: mariadb:latest
        env_file:
            - ./docker/db/slaves/email/.env.slave
        volumes:
            - ./docker/db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
            - ./docker/db/slaves/email/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
            - ./docker/db/slaves/email/.data/mysql:/var/lib/mysql:rw
        ports:
            - "3307:3306"
        networks:
            - highload

    db-sms:
        container_name: db_sms
        image: mariadb:latest
        env_file:
            - ./docker/db/slaves/sms/.env.slave
        volumes:
            - ./docker/db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
            - ./docker/db/slaves/sms/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
            - ./docker/db/slaves/sms/.data/mysql:/var/lib/mysql:rw
        ports:
            - "3308:3306"
        networks:
            - highload

    db-slave-3:
        container_name: db_slave_3
        image: mariadb:latest
        env_file:
            - ./docker/db/slaves/slave_3/.env.slave
        volumes:
            - ./docker/db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
            - ./docker/db/slaves/slave_3/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
            - ./docker/db/slaves/slave_3/.data/mysql:/var/lib/mysql:rw
        ports:
            - "3309:3306"
        networks:
            - highload

    db-slave-4:
        container_name: db_slave_4
        image: mariadb:latest
        env_file:
            - ./docker/db/slaves/slave_4/.env.slave
        volumes:
            - ./docker/db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
            - ./docker/db/slaves/slave_4/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
            - ./docker/db/slaves/slave_4/.data/mysql:/var/lib/mysql:rw
        ports:
            - "3310:3306"
        networks:
            - highload

    node:
        container_name: node
        image: node:latest
        tty: true
        restart: always
        working_dir: /var/www/highload
        volumes:
            - .:/var/www/highload
        depends_on:
            - 'app'
        ports:
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'

networks:
    highload:
        driver: bridge
